### ISSUE TITLE
Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by strataga** [leafty/node-yaml-config#6]
ERROR in ./~/node-yaml-config/lib/node-yaml-config.js

Module not found: Error: Cannot resolve module 'fs' in /.../node_modules/node-yaml-config/lib
 @ ./~/node-yaml-config/lib/node-yaml-config.js 12:9-22

**Comment by leafty** [comment]
This seems to be an issue with the 'n' node version manager. (https://github.com/nodejs/node/issues/9355)
Can reproduce on node >=7.0.0 with 'n' but works fine if using node/npm form official nodejs.org.

Sorry for 2 months late answer.
